import { Document, Font, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Item, Person } from "@/lib/types";

interface InvoicePDFProps {
  items: Item[];
  people: Person[];
  total: number;
  taxApplied: boolean;
  currency: string;
}

Font.register({
  family: "NotoSans",
  src: "/fonts/NotoSans-Regular.ttf",
});

Font.register({
  family: "NotoSans",
  src: "/fonts/NotoSans-Bold.ttf",
  fontWeight: "bold",
});

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 11,
    fontFamily: "NotoSans",
  },
  title: {
    fontSize: 20,
    marginBottom: 20,
    fontWeight: "bold",
  },
  section: {
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  tableHeader: {
    fontWeight: "bold",
    borderBottom: "1 solid #ccc",
    paddingBottom: 4,
    marginBottom: 6,
  },
});

export default function InvoicePDF({ items, people, total, taxApplied, currency }: InvoicePDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Invoice</Text>

        {/* ITEMS */}
        <View style={styles.section}>
          <Text style={styles.tableHeader}>Items</Text>
          {items.map((item, i) => (
            <View key={i} style={styles.row}>
              <Text>
                {item.name} × {item.quantity}
              </Text>
              <Text>{currency}{item.cost.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        {/* PEOPLE SPLIT */}
        <View style={styles.section}>
          <Text style={styles.tableHeader}>Split Summary</Text>
          {people.map((p, i) => (
            <View key={i} style={styles.row}>
              <Text>{p.name}</Text>
              <Text>{currency}{p.owes.toFixed(2)}</Text>
            </View>
          ))}
        </View>

        {/* TOTAL */}
        <View style={styles.section}>
          <View style={styles.row}>
            <Text>Total</Text>
            <Text>{currency}{total.toFixed(2)}</Text>
          </View>
          <Text>
            Tax Applied: {taxApplied ? "Yes" : "No"}
          </Text>
        </View>

        <Text>Date: {new Date().toLocaleDateString()}</Text>
        <Text>Currency: {currency}</Text>

        <Text
          style={{
            position: "absolute",
            bottom: 30,
            left: 30,
            fontSize: 9,
            color: "#666",
          }}
        >
          Generated by Split Calculator
        </Text>
      </Page>
    </Document>
  );
}
